### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by iyobo** [adonisjs/adonis-app#15]
I added a middleware by registering it in Kernel.js and also creating it under the Middleware directory.
However each time I keep getting an **Cannot read property 'toString' of undefined** error.

What's require-stack for? It seems to be the one generating this error....and it seems to be terribly pessimistic and awful at error checking. Why does it expect that an error exists and breaks when it doesn't?

kernel.js
```
const namedMiddleware = {
  'auth':'App/Http/Middleware/Auth'
}
```

Auth.js
```
class Auth {

  *handle (request, response, next) {
    if(true) {
      response.status(401).send("Login first")
      return
    }
    yield next
  }

}
```
Route.js
`Route.get('/dashboard', 'DashboardController.jobseeker').middlewares(['auth'])`

**Comment by iyobo** [comment]
```
Cannot read property 'toString' of undefined TypeError: Cannot read property 'toString' of undefined
    at requireStack (/projects/livinghired/livinghiredonis/node_modules/require-stack/src/index.js:57:31)
    at Object.Ioc._autoLoad (/projects/livinghired/livinghiredonis/node_modules/adonis-fold/src/Ioc/index.js:144:18)
    at Object.Ioc.use (/projects/livinghired/livinghiredonis/node_modules/adonis-fold/src/Ioc/index.js:332:18)
    at Object.Ioc.make (/projects/livinghired/livinghiredonis/node_modules/adonis-fold/src/Ioc/index.js:393:19)
    at Object.Ioc.makeFunc (/projects/livinghired/livinghiredonis/node_modules/adonis-fold/src/Ioc/index.js:443:24)
    at /projects/livinghired/livinghiredonis/node_modules/adonis-framework/src/Middleware/index.js:135:22
    at arrayMap (/projects/livinghired/livinghiredonis/node_modules/adonis-framework/node_modules/lodash/lodash.js:595:23)
    at Function.map (/projects/livinghired/livinghiredonis/node_modules/adonis-framework/node_modules/lodash/lodash.js:7814:14)
    at Object.Middleware.resolve (/projects/livinghired/livinghiredonis/node_modules/adonis-framework/src/Middleware/index.js:134:12)
    at /projects/livinghired/livinghiredonis/node_modules/adonis-framework/src/Server/helpers.js:35:38
    at next (native)
```

**Comment by iyobo** [comment]
Okay I found the problem.
There was an error in my auth middleware ( no 'use strict').
But the error did not propagate properly. 

Maybe errors in app middlewares need to be handled differently?
