### ISSUE TITLE
sqlite error

### ISSUE THREAD

**Issue by belozyorcev** [adonisjs/adonis-app#22]
In ```dev```, then I run  ```$ ./ace migration:run```

```
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/sergey/projects/microel/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sergey/projects/microel/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Client._driver (/home/sergey/projects/microel/node_modules/knex/lib/dialects/sqlite3/index.js:37:12)
    at Client.initializeDriver (/home/sergey/projects/microel/node_modules/knex/lib/client.js:162:26)
    at Client (/home/sergey/projects/microel/node_modules/knex/lib/client.js:41:10)
    at Client_SQLite3 (/home/sergey/projects/microel/node_modules/knex/lib/dialects/sqlite3/index.js:23:10)
    at new Client (/home/sergey/projects/microel/node_modules/knex/lib/util/make-client.js:15:18)
```

sqlite3 installed, but binding __node-v48-linux-x64__

**Comment by thetutlage** [comment]
You may need to re-install `sqlite3`.

**Comment by belozyorcev** [comment]
I'am deleted ```node_modules``` and run ```npm install```  Run => Error
Deleted only ```sqlite3``` and install only ```sqlite3```. Run => Error

**Comment by belozyorcev** [comment]
I'am stupid!
I using ```nvm```.  After the restart OS I forgot to switch on ```nvm use 6```.
All good works! Sorry :smile_cat:

**Comment by thetutlage** [comment]
Np!
