### ISSUE TITLE
MySQL won't install.

### ISSUE THREAD

**Issue by KieronWiltshire** [adonisjs/adonis-app#7]
```C:\Users\C1542295\Projects\dracade>node ./ace migration:run
Knex: run
$ npm install mysql --save
Error: Cannot find module 'mysql'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Client._driver (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\node_modules\knex\lib\dialects\mysql\index.js:35:12)
    at Client.initializeDriver (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\node_modules\knex\lib\client.js:146:26)
    at Client (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\node_modules\knex\lib\client.js:40:10)
    at Client_MySQL (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\node_modules\knex\lib\dialects\mysql\index.js:24:10)
    at new Client (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\node_modules\knex\lib\util\make-client.js:15:18)
    at Knex (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\node_modules\knex\lib\index.js:26:19)
    at new Runner (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\src\Runner\index.js:19:32)
    at Object.closure (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\providers\RunnerProvider.js:17:14)
    at Object.Ioc._resolveProvider (C:\Users\C1542295\Projects\dracade\node_modules\adonis-fold\src\Ioc\index.js:105:53)
    at Object.Ioc.use (C:\Users\C1542295\Projects\dracade\node_modules\adonis-fold\src\Ioc\index.js:330:18)
    at Object.Ioc.make (C:\Users\C1542295\Projects\dracade\node_modules\adonis-fold\src\Ioc\index.js:385:16)
    at Object.Run.handle (C:\Users\C1542295\Projects\dracade\node_modules\adonis-lucid\src\Commands\Run.js:29:22)```

**Comment by KieronWiltshire** [comment]
silly me...
